name: Development - Build and Deployment

on: 
    workflow_dispatch:
    push:
        branches:
            - development
permissions:
  id-token: write
  contents: read

jobs:
    website-build:
        name: Website build
        runs-on: ubuntu-latest
        steps:
            - name: Checking out branch
              uses: actions/checkout@v5
            - name: Restoring cache
              id: cache-npm
              uses: actions/cache@v4
              with:
                path: | 
                  ~/.npm
                  .next/cache
                  node_modules
                key: ${{runner.os}}-${{hashFiles('**/package-lock.json')}}
                restore-keys: ${{runner.os}}-
            - name: Installing dependencies
              run: npm install
            - name: Building website
              run: npm run build
              env:
                DOMAIN: ${{vars.DEV_DOMAIN}}
                EN_AU_DOMAIN: ${{vars.DEV_EN_AU_DOMAIN}}
                ES_MX_DOMAIN: ${{vars.DEV_ES_MX_DOMAIN}}
                ROBOTS: ${{vars.DEV_ROBOTS}}
            - name: Creating artifacts
              uses: actions/upload-artifact@v4
              with:
                name: development
                path: out
                if-no-files-found: error
                retention-days: 1
                compression-level: 9
                overwrite: true
                include-hidden-files: true
    s3-deployment:
      name: Deployment to S3
      runs-on: ubuntu-latest
      needs: website-build
      steps:
        - name: Downloading artifacts
          uses: actions/download-artifact@v4
          with:
            name: development
        - name: Configuring AWS credentials
          uses: aws-actions/configure-aws-credentials@v4.3.1
          with: 
            aws-region: ${{secrets.DEV_AWS_REGION}}
            role-to-assume: ${{secrets.DEV_AWS_ROLE_ARN}}
            role-session-name: FisoCodesDevelopmentDeployment
        - name: Syncing files to S3
          run: aws s3 sync ./ s3://${{secrets.DEV_AWS_S3_BUCKET_NAME}} --delete